SELECT b.AUTHOR_ID, (SELECT AUTHOR_NAME FROM AUTHOR WHERE AUTHOR_ID = b.AUTHOR_ID) AS AUTHOR_NAME, b.CATEGORY, SUM(s.SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK_SALES s
JOIN BOOK b ON s.BOOK_ID = b.BOOK_ID
WHERE DATE_FORMAT(s.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;
