-- 코드를 입력하세요
SELECT b.AUTHOR_ID, 
(
    SELECT a.AUTHOR_NAME
    FROM AUTHOR a
    WHERE b.AUTHOR_ID = a.AUTHOR_ID
) AS AUTHOR_NAME, 
b.CATEGORY, SUM(s.SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK b
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE SALES_DATE like '2022-01%'
    GROUP BY BOOK_ID
) s ON s.BOOK_ID  = b.BOOK_ID
GROUP BY b. AUTHOR_ID, b.CATEGORY
ORDER BY b.AUTHOR_ID ASC, b.CATEGORY DESC;
