SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE, '%Y-%m-%d') AS OUT_DATE, 
CASE
WHEN OUT_DATE is NULL THEN '출고미정'
WHEN DATEDIFF(OUT_DATE, '2022-05-01') > 0 THEN '출고대기'
WHEN DATEDIFF(OUT_DATE, '2022-05-01') <= 0 THEN '출고완료'
END AS '출고여부'
from FOOD_ORDER
order by ORDER_ID;
