SELECT info.ITEM_ID,  info.ITEM_NAME, info.RARITY
FROM ITEM_INFO info 
WHERE info.ITEM_ID NOT IN (
    SELECT PARENT_ITEM_ID FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
ORDER BY info.ITEM_ID desc;