SELECT ins.ANIMAL_ID, ins.NAME
FROM ANIMAL_INS ins
JOIN (
    SELECT i.ANIMAL_ID, DATEDIFF(outs.DATETIME, i.DATETIME) AS M
    FROM ANIMAL_INS i
    JOIN ANIMAL_OUTS outs ON i.ANIMAL_ID = outs.ANIMAL_ID
    WHERE i.ANIMAL_ID in (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
    ORDER BY M DESC
    LIMIT 2
) n on ins.ANIMAL_ID = n.ANIMAL_ID
ORDER BY n.M DESC;
