SELECT DISTINCT c.CAR_ID, 
c.CAR_TYPE
, FLOOR((c.DAILY_FEE - (p.DISCOUNT_RATE * c.DAILY_FEE / 100))*30)
AS FEE
FROM (
    SELECT CAR_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE DURATION_TYPE like '%30%'
) p
JOIN ( 
    SELECT DISTINCT CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단' OR CAR_TYPE = 'SUV'
) c ON c.CAR_TYPE = p.CAR_TYPE
WHERE c.CAR_ID NOT IN
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (START_DATE <= '2022-11-30') AND (END_DATE >= '2022-11-01')
) 
AND (c.DAILY_FEE - (p.DISCOUNT_RATE * c.DAILY_FEE / 100))*30 >= 500000 AND (c.DAILY_FEE - (p.DISCOUNT_RATE * c.DAILY_FEE / 100))*30 < 2000000
ORDER BY  FEE DESC, C.CAR_TYPE ASC, c.CAR_ID DESC;

