-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, CONCAT(u.CITY, " ", u.STREET_ADDRESS1, " ", STREET_ADDRESS2) AS '전체주소', CONCAT(SUBSTRING(u.TLNO, 1, 3), "-", SUBSTRING(u.TLNO, 4, 4), "-", SUBSTRING(u.TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_USER u
JOIN (
    SELECT WRITER_ID, count(*) AS CNT_BOARD
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
) b on b.WRITER_ID = u.USER_ID
WHERE b.CNT_BOARD >= 3
ORDER BY u.USER_ID DESC;
