SELECT DATE_FORMAT(sale.SALES_DATE, '%Y') AS YEAR, DATE_FORMAT(sale.SALES_DATE, '%m') AS MONTH, info.GENDER, COUNT(DISTINCT sale.USER_ID) AS USERS
FROM USER_INFO info
JOIN ONLINE_SALE sale ON info.USER_ID = sale.USER_ID
WHERE info.GENDER IS NOT NULL
GROUP BY DATE_FORMAT(sale.SALES_DATE, '%Y'), DATE_FORMAT(sale.SALES_DATE, '%m'), info.GENDER
ORDER BY YEAR, MONTH, GENDER;