SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(p.PRICE * o.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN (
    SELECT PRODUCT_ID, AMOUNT FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE, "%Y-%m") = '2022-05'
) o ON o.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC;