SELECT fh.FLAVOR
FROM FIRST_HALF fh 
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) j ON j.FLAVOR = fh.FLAVOR
ORDER BY (j.TOTAL_ORDER + fh.TOTAL_ORDER) DESC
limit 3;