SELECT a.APNT_NO, p.PT_NAME, a.PT_NO, a.MCDP_CD, 
(SELECT DR_NAME FROM DOCTOR WHERE a.MDDR_ID = DR_ID)
, a.APNT_YMD AS DR_NAME
FROM APPOINTMENT a
JOIN PATIENT p ON a.PT_NO = p.PT_NO
WHERE a.MCDP_CD like 'CS' AND a.APNT_CNCL_YN like 'N' AND DATE_FORMAT(a.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
ORDER BY a.APNT_YMD;