SELECT u.USER_ID, u.NICKNAME, d.TOTAL_SALES AS TOTAL_SALES
FROM USED_GOODS_USER u
JOIN (
    SELECT SUM(PRICE) AS TOTAL_SALES, WRITER_ID
    FROM USED_GOODS_BOARD
    WHERE STATUS='DONE'
    GROUP BY WRITER_ID
) d on u.USER_ID = d.WRITER_ID
WHERE d.TOTAL_SALES >= 700000
ORDER BY d.TOTAL_SALES;
