SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR, count(*)AS COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H:%m') >= '09:00' AND DATE_FORMAT(DATETIME, '%H:%m') <= '19:59'
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY DATE_FORMAT(DATETIME, '%H');
