SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE m
JOIN (
    SELECT * FROM REST_REVIEW
    WHERE (SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID)  DESC
    LIMIT 1) = MEMBER_ID
) r ON r.MEMBER_ID = m.MEMBER_ID
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC;