SELECT ins.ANIMAL_ID, ins.NAME
FROM ANIMAL_INS ins
JOIN ANIMAL_OUTS outs ON ins.ANIMAL_ID = outs.ANIMAL_ID
WHERE DATE_FORMAT(ins.DATETIME, '%Y-%m-%d %H:%m:%s') > DATE_FORMAT(outs.DATETIME, '%Y-%m-%d %H:%m:%s')
ORDER BY ins.DATETIME;