SELECT ins.ANIMAL_ID, ins.NAME
FROM ANIMAL_INS ins
JOIN (
    SELECT o.ANIMAL_ID FROM ANIMAL_OUTS o
    JOIN ANIMAL_INS i on o.ANIMAL_ID = i.ANIMAL_ID
    WHERE o.DATETIME < i.DATETIME
) outs on outs.ANIMAL_ID = ins.ANIMAL_ID
ORDER BY ins.DATETIME ASC;