SELECT DISTINCT c.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
) c on c.CAR_ID = h.CAR_ID
WHERE MONTH(h.START_DATE) >= 10
ORDER BY c.CAR_ID DESC;

