SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN(
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY like '과자' OR CATEGORY like '국' OR CATEGORY like '김치' OR CATEGORY like '식용유'
    GROUP BY CATEGORY
)
ORDER BY MAX_PRICE DESC;

# select * from food_product;
# 	8950
#     19000
#     2900
#     1950